name: Update X4B.Net processing repo
on:
  push:
    paths:
    - 'ipv4.txt'
    branches:
    - main
  workflow_dispatch:

jobs:
  commit:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Push IPv4 to processing repository
      uses: splitice/copy_file_to_another_repo_action@main
      env:
        API_TOKEN_GITHUB: ${{ secrets.MY_GITHUB_TOKEN }}
      with:
        source_file: 'ipv4.txt'
        destination_repo: 'X4Bnet/cfg_lists'
        destination_folder: '/input/'
        rename: vpn.list
        user_email: 'automated@x4b.net'
        user_name: 'listbuilder'
        destination_branch: "main"

